image:
#  - Ubuntu1804
#  - Ubuntu2004
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  USE_BAZEL_VERSION: 5.0.0
  BAZELISK_VERSION: 1.11.0
  VCVARSALL: x64
  platform: "x64"

for:
#-
#  matrix:
#    only:
#      - image: Ubuntu1804
#      - image: Ubuntu2004
#  environment:
#    BAZELISK_BINARY: bazelisk-linux-amd64
#    BAZEL_BINARY: bazel
-
  matrix:
    only:
      - image: Visual Studio 2017
  environment:
    VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio"\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
    GYP_MSVS_VERSION: 2017
    BAZELISK_BINARY: bazelisk-windows-amd64.exe
    BAZEL_BINARY: bazel.exe
-
  matrix:
    only:
      - image: Visual Studio 2019
  environment:
    VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
    GYP_MSVS_VERSION: 2019
    BAZELISK_BINARY: bazelisk-windows-amd64.exe
    BAZEL_BINARY: bazel.exe

init:
  - cmd: call %VCVARSALLPATH% %VCVARSALL%

install:
  # Create a bin folder where bazelisk will be located and add it in the path
  - ps: New-Item -Type dir "$env:HOME\bin"
  - ps: |
      if ($isLinux) {
        $env:PATH += ":$env:HOME/bin"
      } else {
        $Env:Path += ";$env:HOME/bin"
      }
      echo $env:BAZELISK_VERSION
  # Download bazelisk from github
  - ps: Invoke-Webrequest "https://github.com/bazelbuild/bazelisk/releases/download/v$env:BAZELISK_VERSION/$env:BAZELISK_BINARY" -OutFile "$env:BAZELISK_BINARY"
  # Renaming bazelisk to bazel is quite a common practice, people got used to run bazel build and not bazelisk build
  - ps: Copy-Item -Path "$env:BAZELISK_BINARY" -Destination "$env:HOME\bin\$env:BAZEL_BINARY" -Recurse
  - sh: chmod +x $HOME/bin/bazel

build_script:
#  - cmd: pwsh .\script.ps1
  - cmd: |
       bazel run %BUILDARGS% //qt:runanki -k --verbose_failures
 #     bazel.exe build -k -c opt dist --color=yes
 # - sh: pwsh -File script.ps1