# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
          logLevel:
            description: 'Log level'
            required: true
            default: 'info'
jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "C:/Users/runneradmin/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        dir env:
        #curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-windows-amd64.exe"
        mkdir "${GITHUB_WORKSPACE}/bin/"
        #mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        mv bazelisk-windows-amd64.exe "${GITHUB_WORKSPACE}\bin\bazel.exe"
        #chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test
      run: |
        rm bazel.bat
        $env:Path +=";${GITHUB_WORKSPACE}\bin"
        .\bin\bazel.exe -k -c opt dist --color=yes
#        \bin\bazel.exe test ...

  #  - name: Build
  #    run: |
  #      "${GITHUB_WORKSPACE}/bin/bazel" build //...
